config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "home#top"

  get "/users"             , to: "users#index"
  get "/signup"            , to: "users#new"
  post "/users/create"     , to: "users#create"
  get "/users/:id"         , to: "users#show"
  get "/users/:id/edit"    , to: "users#edit"
  post "/users/:id/update" , to: "users#update"
  post "/users/:id/destroy", to: "users#destroy"
  get "/login"             , to: "users#login_form"
  post "/login"            , to: "users#login"
  post "/logout"           , to: "users#logout"

  get "/problems"         , to: "problems#index"
  get "/problems/new"     , to: "problems#new"
  get "/problems/abc"     , to: "problems#abc"
  get "/problems/arc"     , to: "problems#arc"
  get "/problems/agc"     , to: "problems#agc"
  get "/problems/other"   , to: "problems#other"
  get "/problems/:task_id", to: "problems#show"
  post "/problems/create" , to: "problems#create"

  get "/questions"                               , to: "questions#index"
  get "/problems/:task_id/questions/new"         , to: "questions#new"
  post "/problems/:task_id/questions/create"     , to: "questions#create"
  get "/problems/:task_id/questions/:id"         , to: "questions#show"
  get "/problems/:task_id/questions/:id/edit"    , to: "questions#edit"
  post "/problems/:task_id/questions/:id/update" , to: "questions#update"
  post "/problems/:task_id/questions/:id/destroy", to: "questions#destroy"

  get "/problems/:task_id/questions/:question_id/answers"             , to: "answers#index"
  get "/problems/:task_id/questions/:question_id/answers/new"         , to: "answers#new"
  post "/problems/:task_id/questions/:question_id/answers/create"     , to: "answers#create"
  get "/problems/:task_id/questions/:question_id/answers/:id/edit"    , to: "answers#edit"
  post "/problems/:task_id/questions/:question_id/answers/:id/update" , to: "answers#update"
  post "/problems/:task_id/questions/:question_id/answers/:id/destroy", to: "answers#destroy"
  put "/problems/:task_id/questions/:question_id/answers/:id/like"  ,   to: "answers#upvote"
  put "/problems/:task_id/questions/:question_id/answers/:id/unlike",   to: "answers#downvote"
  put "/problems/:task_id/questions/:question_id/answers/:id/cancel_like"  ,   to: "answers#cancel_upvote"
  put "/problems/:task_id/questions/:question_id/answers/:id/cancel_unlike"  ,   to: "answers#cancel_downvote"
end

app/models/problem.rb
class Problem < ApplicationRecord
  def duplicated?(target_problem)
    if self.task_id == target_problem.task_id
      return true
    else
      return false
    end
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def index
    abc
  end

  def show
    @problem = Problem.find_by(task_id: params[:task_id])
    @questions = Question.where(task_id: @problem.task_id).order(created_at: :desc)
  end

  def new
    @problem = Problem.new
  end

  def create
    require 'json'

    contests_api = 'https://kenkoooo.com/atcoder/resources/contests.json'
    contests = fetch_api_in_json_format contests_api

    contests.each do |contest_api|
      unless Contest.find_by(contest_id: contest_api["id"])
        contest = Contest.new(
          contest_id: contest_api["id"],
          start_epoch_second: contest_api["start_epoch_second"],
          title: contest_api["title"],
        )

        if contest.save
        else
          logger.debug("DEBUG: " + "Failed to save the contest" + "#{contest.inspect}")
        end
      end
    end

    problems_api = 'https://kenkoooo.com/atcoder/resources/problems.json'
    problems = fetch_api_in_json_format problems_api

    problems.each do |problem_api|
      unless Problem.find_by(task_id: problem_api["id"])
        problem = Problem.new(
          task_id: problem_api["id"],
          contest_id: problem_api["contest_id"],
          title: problem_api["title"],
        )

        if problem.save
        else
          logger.debug("DEBUG: " + "Failed to save the problem" + "#{problem.inspect}")
        end
      end
    end

    # 同じ日に開催されたコンテストで，重複する問題に対処
    contests_problems_api = 'https://kenkoooo.com/atcoder/resources/contest-problem.json'
    contests_problems = fetch_api_in_json_format contests_problems_api

    contests_problems.each do |contest_problem|
      unless Problem.find_by(contest_id: contest_problem["contest_id"], task_id: contest_problem["problem_id"])
        problem_title = Problem.find_by(task_id: contest_problem["problem_id"]).title

        problem = Problem.new(
          task_id: contest_problem["problem_id"],
          contest_id: contest_problem["contest_id"],
          title: problem_title,
        )

        if problem.save
        else
          logger.debug("DEBUG: " + "Failed to save the problem" + "#{problem.inspect}")
        end
      end
    end

    flash[:notice] = "Updated!"
    redirect_to("/problems/new")
  end

  def abc
    @selected_problems = Contest.abc.page(params[:page]).per(5)
    @contest_type = "AtCoder Beginner Contest"

    render("problems/index")
  end

  def arc
    @selected_problems = Contest.arc.page(params[:page]).per(5)
    @contest_type = "AtCoder Regular Contest"

    render("problems/index")
  end

  def agc
    @selected_problems = Contest.agc.page(params[:page]).per(5)
    @contest_type = "AtCoder Grand Contest"

    render("problems/index")
  end

  def other
    @selected_problems = Contest.others.page(params[:page]).per(5)
    @contest_type = "Other Contests"

    render("problems/index")
  end

private
  def fetch_api_in_json_format(url)
    response = Faraday.get url
    response_body = response.body.force_encoding("UTF-8")
    response_body_to_json = JSON.parse(response_body)
    return response_body_to_json
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_problem.html.slim
.card-body
  h3.card-title
    = title

  / Dummy space
  p
    |

    = paginate contests

    - contests.each do |contest|
      - problems = Problem.where(contest_id: contest.contest_id).order(:task_id)

      - problems.each do |problem|
        - atcoder = "https://atcoder.jp/contests/"
        - url = atcoder + problem.contest_id + "/tasks/" + problem.task_id

        ul.list-group.list-group-flash
          li.list-group-item

            .problems__wrapper
              h4.problems__title
                = link_to("#{contest.title + ": " + problem.title}", "#{url}", target: '_blank')

              / See:
              / https://www.nxworld.net/tips/flexbox-examples.html
              .problems__questions
                - questions = Question.where(task_id: problem.task_id)
                - questions_count = questions.count

                - if questions_count > 0
                  - comment = fa_icon "comment", class: "problems__questions--comment"
                  = link_to(comment + " " + questions_count.to_s, "/problems/#{problem.task_id}")

            .problems__qa-board-button
              = link_to("Go Q&A board ▶︎", "/problems/#{problem.task_id}", class: "btn btn-success btn-sm abc")

    = paginate contests

app/views/problems/index.html.slim
.main
  .problems-wrapper
    .container
      .heading
        .problems
          = render "problem", contests: @selected_problems, title: @contest_type

app/views/problems/new.html.slim
.main
  .problems-wrapper
    .container
      .heading
        .problems
          = link_to("Show", "/problems/create", {class: "btn btn-success btn-sm abc", method: "post"})

app/views/problems/show.html.slim
.main
  .problems-wrapper
    .container
      .heading
        .problems
          - atcoder = "https://atcoder.jp/contests/"
          - url = atcoder + @problem.contest_id + "/tasks/" + @problem.task_id

          h2
            = link_to("#{@problem.contest_id.upcase + ": " + @problem.title}", url, target: "_blank")

          / ログイン状態のときだけ質問の投稿を許可する
          - if @current_user
            = link_to("New Question", "/problems/#{@problem.task_id}/questions/new", class: "btn btn-success btn-sm")

          / FIXME: CSSで配置を調整する
          br
          br

          / DBから該当する問題の質問のみ抽出
          - exclamation = fa_icon "exclamation-circle"
          - check = fa_icon "check"
          - space = " "

          .card
            .card-header
              / dummy value
              = exclamation + space + 26.to_s + space + "Open" + space + check + space + 10.to_s + space + "Closed"

            ul.list-group.list-group-flush
              - @questions.each do |question|

                li.list-group-item
                  .questions
                    .questions__left
                      .question__status
                        = fa_icon "exclamation-circle"

                    .questions__right
                      .questions__title
                        - url = "/problems/#{@problem.task_id}/questions/#{question.id}"
                        = link_to("#{question.title}", "#{url}")

                      - answers = Answer.where(question_id: question.id)
                      - answers_count = answers.count

                      - if answers_count > 0
                        .question__answers--comment
                            = fa_icon "comment"

                        .question__answers--count
                            = link_to(answers_count, url)

                    .questions__bottom
                      .question__post-info
                        = "Posted" + space + time_ago_in_words(question.created_at) + space + "ago" + space + "by" + space

                        span.question__post-info--posted-user
                          = link_to(question.user.name, "/users/#{question.user.id}")

          / TODO: 入力フォームを用意

          p

          - problems_url = nil

          - if @problem.task_id =~ /abc\d{3}/
            - problems_url = "/problems/abc"
          - elsif @problem.task_id =~ /arc\d{3}/
            - problems_url = "/problems/arc"
          - elsif @problem.task_id =~ /agc\d{3}/
            - problems_url = "/problems/agc"
          - else
            - problems_url = "/problems/other"

          = link_to("◀ Return to list", problems_url, class: "btn btn-outline-secondary btn-sm")